services:
  ms_kitchen_db:
    image: postgres:15
    container_name: ms_kitchen_db
    environment:
      - POSTGRES_DB=${MS_KITCHEN_DB_NAME}
      - POSTGRES_USER=${MS_KITCHEN_DB_USER}
      - POSTGRES_PASSWORD=${MS_KITCHEN_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-kitchen:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bbg -d ddd_database"]
      interval: 10s
      timeout: 5s
      retries: 5
  ms_kitchen_api:
    image: bladibap/catering_produccion:1.0.1
    container_name: ms_kitchen_api
    environment:
      - DB_HOST=${MS_KITCHEN_DB_HOST}
      - DB_PORT=${MS_KITCHEN_DB_PORT}
      - DB_USER=${MS_KITCHEN_DB_USER}
      - DB_PASSWORD=${MS_KITCHEN_DB_PASSWORD}
      - DB_NAME=${MS_KITCHEN_DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - code-kitchen:/src
    depends_on:
      ms_kitchen_db:
        condition: service_healthy

volumes:
  postgres-data-kitchen:
  code-kitchen: